---
title: Flujo de trabajo para preparar variables
---
flowchart LR
  raster_fuente1@{shape: doc, label: "Capa raster fuente individuales en formato GeoTIFF .tif"}
  raster_fuente2@{shape: doc, label: "Capa raster fuente individuales en formato GeoTIFF .tif"}
  raster_fuente3@{shape: doc, label: "Capa raster fuente individuales en formato GeoTIFF .tif"}
  raster_fuente4@{shape: doc, label: "Capa raster fuente individuales en formato GeoTIFF .tif"}
  raster_fuente5@{shape: doc, label: "Capa raster fuente individuales en formato GeoTIFF .tif"}
  raster_fuente6@{shape: doc, label: "Capa raster fuente individuales en formato GeoTIFF .tif"}
  stack_por_tipo1@{shape: docs, label: "Raster stack con capas agrupados segun tipo, tamaño de pixel y su extensión en formato GeoTIFF .tif"}
  stack_por_tipo2@{shape: docs, label: "Raster stack con capas agrupados segun tipo, tamaño de pixel y su extensión en formato GeoTIFF .tif"}
  stack_homologado1@{shape: docs, label: "Raster stack con tamaños de pixel homologado en formato GeoTIFF .tif"}
  stack_homologado2@{shape: docs, label: "Raster stack con tamaños de pixel homologado en formato GeoTIFF .tif"}
  stack_completo@{shape: docs, label: "Raster stack completo recortado en formato GeoTIFF .tif"}
  asc1@{shape: doc, label: "Capa indivial en formato ESRI ASCII grid .asc"}
  asc2@{shape: doc, label: "Capa indivial en formato ESRI ASCII grid .asc"}
  asc3@{shape: doc, label: "Capa indivial en formato ESRI ASCII grid .asc"}
  asc4@{shape: doc, label: "Capa indivial en formato ESRI ASCII grid .asc"}
  asc5@{shape: doc, label: "Capa indivial en formato ESRI ASCII grid .asc"}
  asc6@{shape: doc, label: "Capa indivial en formato ESRI ASCII grid .asc"}
  raster_fuente1 --gdal_merge--> stack_por_tipo1 
  raster_fuente2 --gdal_merge--> stack_por_tipo1 
  raster_fuente3 --gdal_merge--> stack_por_tipo1 
  raster_fuente4 --gdal_merge--> stack_por_tipo2 
  raster_fuente5 --gdal_merge--> stack_por_tipo2 
  raster_fuente6 --gdal_merge--> stack_por_tipo2 
  stack_por_tipo1 --gdal_translate--> stack_homologado1
  stack_por_tipo2 --gdal_translate--> stack_homologado2
  stack1_homologado1 --gdal_merge--> stack_completo
  stack2_homologado1 --gdal_merge--> stack_completo
  stack_completo --gdal_translate--> asc1 
  stack_completo --gdal_translate--> asc2 
  stack_completo --gdal_translate--> asc3 
  stack_completo --gdal_translate--> asc4 
  stack_completo --gdal_translate--> asc5 
  stack_completo --gdal_translate--> asc6 
