---
title: "T downscaling TMax month 01 model polynomic"
author: "Viacheslav Shalisko"
date: "16 de abril de 2018"
output: html_document
---

### Some important variables

```{r set-variables}
# random numbers seed
set.seed(1)

rpoints_mask1_number <- 10000
rpoints_mask2_number <- 10000

# month to be analysed (in current version the analysis is per month)
month <- 1

# dependent variable to be analysed
var_dependent <- "tmax"
var_dependent_name <- "Maximum temperature"

# geographic coordinate system string
mi_crs <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

# map extent
# all data should be in geographic coodinates
ext_vector <- c(-120,-30,-50,50)

# output directory (relative to curretnt dir)
output_path <- 'C:/Users/vshal/Downloads/SDM_interpolations/models'

# name of low resolution source dependent variable
r_lores_name <- "C:/Users/vshal/Downloads/SDM_interpolations/wc2_30s_tmax_01_Amer_F1.tif"

# name of high resolution predictor variable
r_predictor_name <- "C:/Users/vshal/Downloads/SDM_recortes/gmted_med075_Amer.tif"

# names of first and second high resolution masks
r_mask1_name <- "C:/Users/vshal/Downloads/SDM_recortes/Continents_Amer_S1a.tif"
r_mask2_name <- "C:/Users/vshal/Downloads/SDM_recortes/Continents_Amer_S2a.tif"

```

```{r load-libs}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)

library(raster)       # raster processing
library(maptools)     # map processing
library(rworldmap)    # worldmap datasets
library(rworldxtra)   # hires worldmap spatial dataframe
library(dismo)        # SDM, here used to generate random points
library(mgcv)         # GAM models
```

### Read source raster data

```{r read-rasters}
r_lores <- raster(r_lores_name)
r_predictor <- raster(r_predictor_name)
r_mask1 <- raster(r_mask1_name)
r_mask2 <- raster(r_mask2_name)
```

### Produce random points

```{r generate-sampling-points, cache=TRUE}
random_points_mask1 <- randomPoints(r_mask1, n = rpoints_mask1_number, tryf = 3)
random_points_mask2 <- randomPoints(r_mask2, n = rpoints_mask2_number, tryf = 5)

dim(random_points_mask1)
dim(random_points_mask2)

random_points_all <- rbind(random_points_mask1,random_points_mask2)
```

### Render random points

```{r data-visualization, fig.width=12, fig.height=14}
# background continents
plot(random_points_mask1, col='red',cex=0.7, xlim=ext_vector[1:2], ylim=ext_vector[3:4], axes=TRUE)
world_high <- getMap(resolution = "high")
plot(world_high, add=TRUE)

# render random points
points(random_points_mask2,col='blue',cex=0.7)
```

### Sample raster data

```{r sample-rasters, cache=TRUE}

values_T <- extract(r_lores, random_points_all)
values_A <- extract(r_predictor, random_points_all)
values_Y <- random_points_all[,"y"]
values_X <- random_points_all[,"x"]

# remove NAs
intermediate_frame <- data.frame(values_X, values_Y, values_T, values_A)
intermediate_frame <- na.omit(intermediate_frame)

T <- as.vector(intermediate_frame[,3])
A <- as.vector(intermediate_frame[,4])
Y <- as.vector(intermediate_frame[,2])
X <- as.vector(intermediate_frame[,1])
```

### Resumen of sampled values

```{r data-summary, fig.width=12}
par(mfrow=c(1, 2))
hist(T, col = "lightgray", xlab = "T (°C)")
hist(A, col = "lightgray", xlab = "Elevation (msnm)")
```

### Produce two-variable polynomic model

```{r model, fig.width=12, fig.height=14}
mod_P1 <- lm(T ~ A + Y + I(Y^2) + I(A*Y) + I(A*Y^2))
summary(mod_P1)
AIC(mod_P1)
```

### Visualize model

```{r model-vis, fig.width=12, fig.height=8}
par(mfrow=c(1, 2))

Aseq <- seq(from=0,to=6000,by=20)
Yseq <- seq(from=-50,to=50,by=1)
AseqD <- seq(from=0,to=6000,by=500)
YseqD <- seq(from=-50,to=50,by=10)

# empty plot for T from altitude  
TA <- predict(mod_P1, newdata = data.frame(A=Aseq,Y=rep(0,length(Aseq))))
plot(Aseq, TA, type = "n", ylab = "T", xlab = "Altitude (msnm)",
     xlim = c(0,7000), ylim = c(-10,40))
YseqD_col <- topo.colors(length(YseqD))

# draw lines for T from altitude by latitude class
for (i in 1:length(YseqD)) {
  Ti <- predict(mod_P1, newdata = data.frame(A=Aseq,Y=rep(YseqD[i],length(Aseq))))
  lines(Aseq, Ti, col = YseqD_col[i])
}

legend("topright", legend = YseqD, title = "Latitude",
  lty = rep(1,length(YseqD)), col = YseqD_col)


# empty plot for T from latitude  
TY <- predict(mod_P1, newdata = data.frame(Y=Yseq,A=rep(0,length(Yseq))))
plot(Yseq, TY, type = "n", ylab = "T", xlab = "Latitude (grad)",
     xlim = c(-50,60), ylim = c(-10,40))
AseqD_col <- topo.colors(length(AseqD))

# draw lines for T from latitude by altitude class
for (i in 1:length(AseqD)) {
  Ti <- predict(mod_P1, newdata = data.frame(Y=Yseq,A=rep(AseqD[i],length(Yseq))))
  lines(Yseq, Ti, col = AseqD_col[i])
}

legend("topright", legend = AseqD, title = "Altitude",
  lty = rep(1,length(AseqD)), col = AseqD_col)
```

## Residuals

```{r resiuals-vis, fig.width=12, fig.height=8}
par(mfcol = c(1, 2))
plot(mod_P1)

residuals_mod_P1 <- resid(mod_P1, type = "pearson")
acf(residuals_mod_P1, main="Standarized residual ACF")
pacf(residuals_mod_P1, main="Standarized residual pACF")

```

### Spatial distribution of residuals

```{r residuals-map, fig.width=12, fig.height=14}
# add residuals to spatial points dataframe
residuals_mod_P1_sp <- SpatialPointsDataFrame(
                  data.frame(X, Y), data.frame(resids = residuals_mod_P1),
                  proj4string = CRS(mi_crs))

# plot residuals
bubble(residuals_mod_P1_sp, zcol='resids', scales = list(draw = TRUE),
       col = c("coral", "lightblue"), main = "Distribution of residuals",
       key.space = list("bottom"))
```

