Zinnia spp.
========================================================



```{r}
library(rgdal)
library(maptools)
library(raster)
library(dismo)

my_factor.as.numeric <- function (f) { as.numeric(levels(f))[f] }

```

Cargando variables

```{r fig.width=10, fig.height=10, cache=TRUE}
my_path <- 'C:\\Users\\Viacheslav\\Google Drive\\Projects_actual\\geo_BioclimInterpolation_Occidente\\Bioclim_a100\\'

#b <- stack(paste(my_path,"biovars_occidente_a1min.tif",sep=""))
b <- stack(paste(my_path,"biovars_primnev_urb_a100.tif",sep=''))
#r <- raster(paste(my_path,"FP2DAR_2015_Urb_a100.tif",sep=''))
#b <- addLayer(b, r)            

names_b <- c(paste('b',1:19,sep=''))
names(b) <- c(names_b,'bosque')

b
summary(b)

mask_reclass_table <- matrix(c(-Inf, Inf, 1), ncol=3, byrow=TRUE)
b_mask <- reclassify(subset(b,1),mask_reclass_table)

#b_mask <- mask(subset(b,1),subset(b,1),updatevalue=1)

plot(b_mask)
plot(b,c(1:9), nc=3)
plot(b,c(10:18), nc=3)
plot(b,c(19:20), nc=3)
```

Cargando puntos de presencia

```{r}
obs_points <- read.csv("Zinnia_para_modelo.csv")

obs_points
obs_points_xy <- data.frame(cbind(obs_points[,2],obs_points[,3]))
colnames(obs_points_xy) <- c('x','y')

data(wrld_simpl)
plot(wrld_simpl, xlim=c(-110,-90), ylim=c(10,30), axes=TRUE, col="lightyellow")

points(obs_points_xy$x, obs_points_xy$y, col="red", cex=0.75)
```

Generando puntos aleatorios (fondo)

```{r}
set.seed(0)
random_bg <- randomPoints(b_mask, 1000)

plot(wrld_simpl, xlim=c(-110,-90), ylim=c(10,30), axes=TRUE, col="lightyellow")
points(random_bg, cex=0.2, col="blue")
points(obs_points_xy$x, obs_points_xy$y, col="red", cex=0.75)

pb <- c(rep(1, nrow(obs_points_xy)), rep(0, nrow(random_bg)))

all_points_xy <- data.frame(cbind(pb, rbind(obs_points_xy, random_bg)))
#dim(all_points_xy)
```

Muestreo de variables

```{r fig.width=10, fig.height=10}
all_vals <- extract(b, all_points_xy[,2:3])

all_vals_xy <- data.frame(cbind(all_points_xy, all_vals))
all_vals_xy <- na.omit(all_vals_xy)

pairs(all_vals_xy[all_vals_xy$pb==1,4:23], cex=0.1, fig=TRUE)
```

Separación de "trainset" y "testset"

```{r}
train_test <- sample(nrow(all_vals_xy), round(0.75 * nrow(all_vals_xy)))
traindata <- all_vals_xy[train_test,]
paste('Número de puntos de entrenamiento:',nrow(traindata[traindata$pb==1,]),sep=' ')
#traindata[traindata$pb==1,]
testdata <- all_vals_xy[-train_test,]
paste('Número de puntos de control:',nrow(traindata[testdata$pb==1,]),sep=' ')
#testdata[testdata$pb==1,]
```

Modelación

```{r fig.width=10, fig.height=10}

jar <- paste(system.file(package='dismo'), '/java/maxent.jar', sep='')
if (file.exists(jar)) {
  bc_model <- maxent(b, obs_points_xy, factors='bosque')
  plot(bc_model)
  
  str(bc_model)
  response(bc_model)
  
  #plot(bc_model, a=4, b=5, p=0.85)

} else {
  print('maxent.jar no disponible')
}

#pb <- predict(b, bc_model, progress='window')
#pb
#plot(pb, main='Modelo MAXENT')
```

Evaluación

```{r fig.width=10, fig.height=5}
e <- evaluate(testdata[testdata$pb==1,], testdata[testdata$pb==0,], bc_model)
e
#str(e)

par(mfrow=c(1, 3))
plot(e, 'ROC')
density(e)
boxplot(e, col=c('lightblue','coral'), notch=TRUE)
```

Evaluación parte 2

```{r fig.width=10, fig.height=5}
test_presence <- extract(pb,testdata[testdata$pb==1,2:3])
test_absence <- extract(pb,testdata[testdata$pb==0,2:3])

test_pb = c(rep('presence', length(test_presence)), rep('absence', length(test_absence)))
test_points <- data.frame(cbind(test_pb, c(test_presence,test_absence)))
colnames(test_points) <- c('obs','prob')
test_points$obs <- as.factor(test_points$obs)
test_points$prob <- my_factor.as.numeric(test_points$prob)

par(mfrow=c(1, 3))
boxplot(prob~obs, data=test_points, col=c('lightblue','coral'), notch=TRUE)
```

Guardando raster

```{r}
if (require(rgdal)) {
  rf <- writeRaster(pb, filename="Zinnia_maxent_superficie_a100.tif", format="GTiff", overwrite=TRUE)
}

```

