---
title: "Loader test"
author: "Viacheslav Shalisko"
date: "12 of november 2017"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)

library(sp)
library(raster)
library(dismo)
```


```{r set-variables}
run_code <- '25'
basepath <- 'C:/Users/vshal/Downloads/R/'
basename <- 'Magnolia_mercedesiarum_MAXENT_HR_'
scriptpath <- 'C:/Users/vshal/OneDrive/Documentos_para_GD/Temp_Magnolia/test_run'

random_seed_folding <- 1
random_seed_background <- 1
random_background_number <- 100

presence_points_count <- 22

layers_to_drop <- c(2,6,7,9,11,12,14,15,17,18,19)
```


```{r cross-validation-load}
iterations <- readRDS(paste(scriptpath, "/iterations_object_",run_code,".rds",sep=""))

#str(iterations)
```

```{r cross-validation-analysis}
auc_mean_vector <- sapply(iterations, function(x) x$auc_null_model_mean)
auc_mean_vector

auc_rank_train_vector <- sapply(iterations, function(x) x$auc_rank_train)
auc_rank_train_vector

auc_rank_test_vector <- sapply(iterations, function(x) x$auc_rank_test)
auc_rank_test_vector

auc_train_vector <- sapply(iterations, function(x) x$e_train$e@auc)
auc_train_vector

auc_test_vector <- sapply(iterations, function(x) x$e_test$e@auc)
auc_test_vector

auc_set <- cbind(auc_mean_vector,auc_rank_train_vector,auc_rank_test_vector,auc_train_vector,auc_test_vector)
colnames(auc_set) <- c("Mean null-model AUC", "Training AUC rank", "Test AUC rank", "Training AUC", "Test AUC")

threshold_test_max_spec_sens_vector <- sapply(iterations, function(x) x$e_test$t$spec_sens)
threshold_test_max_spec_sens_vector

threshold_test_eq_spec_sens_vector <- sapply(iterations, function(x) x$e_test$t$equal_sens_spec)
threshold_test_eq_spec_sens_vector

threshold_train_max_spec_sens_vector <- sapply(iterations, function(x) x$e_train$t$spec_sens)
threshold_train_max_spec_sens_vector

threshold_train_eq_spec_sens_vector <- sapply(iterations, function(x) x$e_train$t$equal_sens_spec)
threshold_train_eq_spec_sens_vector

threshold_set <- cbind(threshold_test_max_spec_sens_vector,
                       threshold_train_max_spec_sens_vector,
                       threshold_test_eq_spec_sens_vector,
                       threshold_train_eq_spec_sens_vector)
colnames(threshold_set) <- c("Test MSS", "Training MSS", "Test ESS", "Training ESS")
```

```{r cross-validation-plot, fig.height=5, fig.width=10}
par(mfrow=c(1, 2))
boxplot(auc_set[,2:3])
boxplot(auc_set[,c(1,4,5)])

boxplot(threshold_set[,1:2])
boxplot(threshold_set[,3:4])
```

```{r cross-validation-roc-plot, fig.height=5, fig.width=10}
par(mfrow=c(1, 2))
col_palette <- palette(topo.colors(3))
cross_validation_lenght <- 10

my_test_roc_plot <- plot(0,0, ylim = c(0,1), xlim = c(0,1), main = 'ROC test', ylab = 'TPR', xlab = 'FPR')

for (j in 1:cross_validation_lenght) {
  my_obj <- iterations[[j]]
  my_test_roc_plot <- lines(my_obj$e_test$e@FPR,my_obj$e_test$e@TPR, col = col_palette[j])
}

my_train_roc_plot <- plot(0,0, ylim = c(0,1), xlim = c(0,1), main = 'ROC train', ylab = 'TPR', xlab = 'FPR')

for (j in 1:cross_validation_lenght) {
  my_obj <- iterations[[j]]
  my_train_roc_plot <- lines(my_obj$e_train$e@FPR,my_obj$e_train$e@TPR, col = col_palette[j])
}

for (j in 1:cross_validation_lenght) {
  my_obj <- iterations[[j]]
  str(my_obj)
  #str(my_obj$auc_null_model_mean)

  #plot(my_obj$e_train$e, 'ROC')
  #print(my_obj$e_train)
  #iterations[j]$e_train$e@auc
  
}

```

