---
title: "Envirem"
author: "Viacheslav Shalisko"
date: "14/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(raster)
library(rgdal)
library(dismo)
library(envirem)

```

```{r}
## read in a climatic raster for use as a template
#rasterTemplate <- raster('D:/Downloads_bak/Climond2/wc2.1_2.5m_clip/wc2.1_2.5m_tmax_clip_01.tif')

## calculate monthly solar radiation, defined for the year 2000, output to the current directory
#ETsolradRasters(rasterTemplate = rasterTemplate, year = 50, outputDir = 'D:/Downloads_bak/Climond2/wc2.1_2.5m_clip/', overwrite = TRUE)
```

```{r}
wcFiles <- list.files('D:/Downloads_bak/Climond2/wc2.1_2.5m_clip/', pattern = 'wc2.1_2.5m', full.names = TRUE)
wcStack <- stack(wcFiles)
names(wcStack)
#str(wcStack)

solarFiles <- list.files('D:/Downloads_bak/Climond2/wc2.1_2.5m_clip/', pattern = 'et_solrad', full.names = TRUE)
solarStack <- stack(solarFiles)
```


```{r}
assignNames(tmax = "wc2.1_2.5m_tmax_clip_##",
            tmin = "wc2.1_2.5m_tmin_clip_##",
            precip = "wc2.1_2.5m_prec_clip_##",
            solrad = "et_solrad_##"
            )

varnames()
verifyFileStructure('D:/Downloads_bak/Climond2/wc2.1_2.5m_clip/', returnFileNames = FALSE)

# We can verify that variable names will be correctly recognized.
verifyRasterNames(masterstack = wcStack, solradstack = solarStack)
```

```{r}

env_rasters <- layerCreation(masterstack = wcStack, solradstack = solarStack, var = 'all')
plot(env_rasters)

writeRaster(env_rasters, filename = "env_rasters.tif", datatype = "FLT4S",format = "GTiff", overwrite = TRUE) 

```

