---
title: "Script para prediccion con modelo de distribución de Magnolias"
author: "Viacheslav Shalisko y Miguel Angel Muñiz Castro"
date: "23 de julio de 2019 al 15 de agosto de 2020"
output:
  html_document: default
---

# Modelo correlativo de distribución de una especie biológica
# Predicción en el escenario ssp245


```{r variables}
## Nombre de la especie
especie <- "Magnolia vallartensis"

## Prefijo del las capas de salida
especie_prefijo <- "Magnolia_vallartensis"

## Nombre del archivo con registro de ocurrencias
nombre_ocurrencias <- "Basedatosvallartensis.csv"

## Nombre del archivo con el conjunto de raster (predictors)
nombre_rasterstack <- "cur.tif"

## iteraciones de validacion cruzada
cross_validation_lenght <- 10

## numero de puntos aleatorios del fondo
background_number = 1000
```

### Cargar las biblioteces requeridas

```{r}
library(sp)
library(raster)
library(dismo)
library(rJava)
```

## 1) Carger el objeto de modelo

```{r cross-validation-load}
validacion_cruzada <- readRDS(paste0(especie_prefijo,"_object_cv",cross_validation_lenght,".rds"))
```

## 2) Predicción en validación cruzada (econdiciones futuras)

```{r}
## Nombre del archivo con el conjunto de raster (predictors)
nombre_rasterstack <- "fut1.tif"
bio_vars <- stack(nombre_rasterstack)
names(bio_vars) <- c(paste0("b_",1:19),paste0("e_",1:16))
bio_vars

## prediction
for (i in 1:cross_validation_lenght){
  my_obj <- validacion_cruzada[[i]]
  prediccion <- predict(bio_vars, my_obj$modelo, progress='window')
  prediccion
  plot(prediccion, 
       main = paste("Probabilidad de presencia estimada ",i,sep=""))
  
  writeRaster(prediccion, 
              filename = paste(especie_prefijo,"_fut1_probabilidad_32bits_iteracion_",
                               i,".tif",sep = ""), 
             format="GTiff", datatype = "FLT4S", overwrite = TRUE)
  
 especie_reclass_table <- matrix(c(-Inf, my_obj$umbrales$spec_sens, 0, 
                                my_obj$umbrales$spec_sens, Inf, 1), 
                              ncol=3, byrow=TRUE)
 prediccion_presencia <- reclassify(prediccion,especie_reclass_table)
 plot(prediccion_presencia, legend = FALSE,
      main = paste("Probable presencia binaria ",i,sep = ""))
  writeRaster(prediccion_presencia, 
              filename = paste(especie_prefijo,"_fut1_presencia_16bits_iteracion_",
                               i,".tif", sep = ""), 
             format="GTiff", datatype = "INT2S", overwrite = TRUE)
}
```

```{r}
## Nombre del archivo con el conjunto de raster (predictors)
nombre_rasterstack <- "fut2.tif"
bio_vars <- stack(nombre_rasterstack)
names(bio_vars) <- c(paste0("b_",1:19),paste0("e_",1:16))
bio_vars

## prediction
for (i in 1:cross_validation_lenght){
  my_obj <- validacion_cruzada[[i]]
  prediccion <- predict(bio_vars, my_obj$modelo, progress='window')
  prediccion
  plot(prediccion, 
       main = paste("Probabilidad de presencia estimada ",i,sep=""))
  
  writeRaster(prediccion, 
              filename = paste(especie_prefijo,"_fut2_probabilidad_32bits_iteracion_",
                               i,".tif",sep = ""), 
             format="GTiff", datatype = "FLT4S", overwrite = TRUE)
  
 especie_reclass_table <- matrix(c(-Inf, my_obj$umbrales$spec_sens, 0, 
                                my_obj$umbrales$spec_sens, Inf, 1), 
                              ncol=3, byrow=TRUE)
 prediccion_presencia <- reclassify(prediccion,especie_reclass_table)
 plot(prediccion_presencia, legend = FALSE,
      main = paste("Probable presencia binaria ",i,sep = ""))
  writeRaster(prediccion_presencia, 
              filename = paste(especie_prefijo,"_fut2_presencia_16bits_iteracion_",
                               i,".tif", sep = ""), 
             format="GTiff", datatype = "INT2S", overwrite = TRUE)
}
```

```{r}
## Nombre del archivo con el conjunto de raster (predictors)
nombre_rasterstack <- "fut3.tif"
bio_vars <- stack(nombre_rasterstack)
names(bio_vars) <- c(paste0("b_",1:19),paste0("e_",1:16))
bio_vars

## prediction
for (i in 1:cross_validation_lenght){
  my_obj <- validacion_cruzada[[i]]
  prediccion <- predict(bio_vars, my_obj$modelo, progress='window')
  prediccion
  plot(prediccion, 
       main = paste("Probabilidad de presencia estimada ",i,sep=""))
  
  writeRaster(prediccion, 
              filename = paste(especie_prefijo,"_fut3_probabilidad_32bits_iteracion_",
                               i,".tif",sep = ""), 
             format="GTiff", datatype = "FLT4S", overwrite = TRUE)
  
 especie_reclass_table <- matrix(c(-Inf, my_obj$umbrales$spec_sens, 0, 
                                my_obj$umbrales$spec_sens, Inf, 1), 
                              ncol=3, byrow=TRUE)
 prediccion_presencia <- reclassify(prediccion,especie_reclass_table)
 plot(prediccion_presencia, legend = FALSE,
      main = paste("Probable presencia binaria ",i,sep = ""))
  writeRaster(prediccion_presencia, 
              filename = paste(especie_prefijo,"_fut3_presencia_16bits_iteracion_",
                               i,".tif", sep = ""), 
             format="GTiff", datatype = "INT2S", overwrite = TRUE)
}
```

```{r}
## Nombre del archivo con el conjunto de raster (predictors)
nombre_rasterstack <- "fut4.tif"
bio_vars <- stack(nombre_rasterstack)
names(bio_vars) <- c(paste0("b_",1:19),paste0("e_",1:16))
bio_vars

## prediction
for (i in 1:cross_validation_lenght){
  my_obj <- validacion_cruzada[[i]]
  prediccion <- predict(bio_vars, my_obj$modelo, progress='window')
  prediccion
  plot(prediccion, 
       main = paste("Probabilidad de presencia estimada ",i,sep=""))
  
  writeRaster(prediccion, 
              filename = paste(especie_prefijo,"_fut4_probabilidad_32bits_iteracion_",
                               i,".tif",sep = ""), 
             format="GTiff", datatype = "FLT4S", overwrite = TRUE)
  
 especie_reclass_table <- matrix(c(-Inf, my_obj$umbrales$spec_sens, 0, 
                                my_obj$umbrales$spec_sens, Inf, 1), 
                              ncol=3, byrow=TRUE)
 prediccion_presencia <- reclassify(prediccion,especie_reclass_table)
 plot(prediccion_presencia, legend = FALSE,
      main = paste("Probable presencia binaria ",i,sep = ""))
  writeRaster(prediccion_presencia, 
              filename = paste(especie_prefijo,"_fut4_presencia_16bits_iteracion_",
                               i,".tif", sep = ""), 
             format="GTiff", datatype = "INT2S", overwrite = TRUE)
}
```